# Analisis Exploratorio

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [12]:
df = pd.read_csv(
    'GRD.csv',
    encoding='latin-1',
    engine='python',            # use python parser which is more forgiving         
    sep=';'                 # uncomment/adjust if the file uses a different separator
)

df.head()

,COD_HOSPITAL,ID_BENEFICIARIO,SEXO,FECHA_NACIMIENTO,ETNIA,PROVINCIA,COMUNA,NACIONALIDAD,PREVISION,SERVICIO_SALUD,...,FECHAPROCEDIMIENTO1,FECHAINTERV1,ESPECIALIDADINTERVENCION,MEDICOALTA_ENCRIPTADO,USOSPABELLON,IR_29301_COD_GRD,IR_29301_PESO,IR_29301_SEVERIDAD,IR_29301_MORTALIDAD,HOSPPROCEDENCIA
0,107102,77447810,MUJER,18/9/1939,NINGUNO,MARGA MARGA,VILLA ALEMANA,CHILE,FONASA INSTITUCIONAL - (MAI) B,VIÑA DEL MAR QUILLOTA,...,NaN,23/3/2024,OFTALMOLOGÍA,71043147,1.0,22360,"0,4384",0,0,NaN
1,107100,81269680,MUJER,31/5/1952,NINGUNO,VALPARAISO,VIÑA DEL MAR,CHILE,FONASA INSTITUCIONAL - (MAI) D,VIÑA DEL MAR QUILLOTA,...,NaN,NaN,NaN,78588090,NaN,41023,"58,207",3,3,NaN
2,105101,77590791,HOMBRE,17/7/2012,NINGUNO,ELQUI,LA SERENA,CHILE,FONASA INSTITUCIONAL - (MAI) A,COQUIMBO,...,NaN,26/1/2024,"CIRUGÍA DE CABEZA, CUELLO Y MAXILOFACIAL",75735052,2.0,34141,"0,4462",1,1,HOSPITAL SAN PABLO (COQUIMBO)
3,112100,77589537,HOMBRE,3/11/1952,NINGUNO,SANTIAGO,ÑUÑOA,CHILE,FONASA INSTITUCIONAL - (MAI) D,METROPOLITANO ORIENTE,...,NaN,8/4/2024,UROLOGÍA,83828813,1.0,61203,"35,647",3,3,NaN
4,118100,94523630,MUJER,28/2/1994,NINGUNO,CONCEPCION,SAN PEDRO DE LA PAZ,PERÚ,FONASA INSTITUCIONAL - (MAI) C,CONCEPCIÓN,...,NaN,24/9/2024,CIRUGÍA GENERAL,98438434,1.0,61131,"0,7398",1,1,NaN

In [14]:
df.describe()

,COD_HOSPITAL,CONDICIONDEALTANEONATO1,PESORN1,RN1ESTADO,CONDICIONDEALTANEONATO2,PESORN2,RN2ESTADO,CONDICIONDEALTANEONATO3,PESORN3,RN3ESTADO,...,PROCEDIMIENTO25,PROCEDIMIENTO26,PROCEDIMIENTO27,PROCEDIMIENTO28,PROCEDIMIENTO29,PROCEDIMIENTO30,MEDICOINTERV1_ENCRIPTADO,FECHAPROCEDIMIENTO1,MEDICOALTA_ENCRIPTADO,USOSPABELLON
count,1.048575e+06,0.0,115509.000000,94465.000000,0.0,1271.000000,1271.000000,0.0,14.000000,14.000000,...,31350.000000,27361.000000,23976.000000,21006.000000,18246.000000,15998.000000,5.965560e+05,0.0,1.048575e+06,632588.000000
mean,1.145591e+05,NaN,3165.667446,9.050410,NaN,2247.132179,8.597168,NaN,1669.857143,7.571429,...,87.950017,87.984653,87.937450,87.863337,88.050582,87.678529,8.186836e+07,NaN,8.332225e+07,1.388148
std,1.078535e+04,NaN,668.603935,1.066989,NaN,622.546909,1.712334,NaN,612.614555,2.651974,...,18.119481,18.110664,18.078913,18.215817,17.824472,18.591029,9.368093e+06,NaN,9.589202e+06,0.863163
min,1.011000e+05,NaN,100.000000,0.000000,NaN,200.000000,0.000000,NaN,100.000000,0.000000,...,0.140000,0.130000,0.090000,0.120000,0.090000,0.120000,6.698964e+07,NaN,6.698964e+07,0.000000
25%,1.091000e+05,NaN,2855.000000,9.000000,NaN,1902.500000,9.000000,NaN,1545.000000,8.000000,...,89.520000,89.520000,89.520000,89.520000,89.520000,89.520000,7.366486e+07,NaN,7.515274e+07,1.000000
50%,1.141010e+05,NaN,3250.000000,9.000000,NaN,2330.000000,9.000000,NaN,1845.000000,8.500000,...,91.390000,91.390000,91.390000,91.390000,91.350000,91.330000,8.075476e+07,NaN,8.269954e+07,1.000000
75%,1.181050e+05,NaN,3590.000000,9.000000,NaN,2687.500000,9.000000,NaN,2055.000000,9.000000,...,96.390000,96.350000,96.350000,96.350000,96.350000,96.350000,8.763694e+07,NaN,9.167102e+07,1.000000
max,2.007170e+05,NaN,9730.000000,11.000000,NaN,3960.000000,10.000000,NaN,2315.000000,10.000000,...,99.940000,99.980000,99.990000,99.840000,99.980000,99.840000,1.022333e+08,NaN,1.022985e+08,8.000000

In [18]:
nulos = df.isnull().sum()
print(nulos)    

df1 = df.dropna()
print(df1.isnull().sum())  # Verificar que no hay valores nulos

COD_HOSPITAL                0
ID_BENEFICIARIO             0
SEXO                        0
FECHA_NACIMIENTO            0
ETNIA                       0
                        ...
IR_29301_COD_GRD            0
IR_29301_PESO               0
IR_29301_SEVERIDAD          0
IR_29301_MORTALIDAD         0
HOSPPROCEDENCIA        959279
Length: 129, dtype: int64
COD_HOSPITAL           0
ID_BENEFICIARIO        0
SEXO                   0
FECHA_NACIMIENTO       0
ETNIA                  0
                      ..
IR_29301_COD_GRD       0
IR_29301_PESO          0
IR_29301_SEVERIDAD     0
IR_29301_MORTALIDAD    0
HOSPPROCEDENCIA        0
Length: 129, dtype: int64

# Analisis de tendencia